Add new version of run_role wrapper script

diff --git a/tools/util/run_role b/tools/util/run_role
--- a/tools/util/run_role
+++ b/tools/util/run_role
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+echo >&2 "ERROR: This script is deprecated. Use ../run_role.py"
+return 1
+
 if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
   echo >&2 "ERROR: This script needs to be sourced to run correctly"
   exit 1
